module.exports = {
    subject: "Szerveroldali webprogramozás",
    task: "GraphQL & Websocket ZH",
    ignore: [
        ".git/**",
        ".idea/**",
        ".vscode/**",
        "node_modules/**",
        "package-lock.json",
        "zip.js",
        "zipfiles/**",
        "zip.config.js",
        "prettier.config.js",
        "**/*.sqlite",
        "graphql/test/**",
        "websocket/test/**",
        "**/error.log",
        "LICENSE",
        "**/*.md",
        "**/.gitignore",
        "**/.editorconfig",
        "**/.prettierignore",
        "**/.prettierrc",
    ],
};
